### ISSUE TITLE
Hello, fans from twitter

### ISSUE THREAD

**Issue by lucasjinreal** [janhsimon/poser#1]
Hi, followed you on twitter, did this project can visualize animation from mixamo fbx format?

**Comment by janhsimon** [comment]
Hi jinfagang. Yes, this project can load animated FBX files from mixamo, I have used that during testing. It uses the assimp library to load animation data, so it should be relatively robust. There are however limitations: Only skeletal animation is supported (no object animations), and only the first animation is loaded if multiple are available.

Having said that, it should be pretty easy to improve this. If you do get a chance to do so, don't hesitate to create a pull request.

**Comment by lucasjinreal** [comment]
@janhsimon Hi, of course! and am exactly need the skeleton animation only! However, when I compile your code ,found some thing weird caused core dump, can u help me out?

```
libc++abi: terminating with uncaught exception of type std::out_of_range: vector
```

I didn't change anything in the code ,do u know why? the only change is I am using fbx animation downloaded from Mixamo.

**Comment by lucasjinreal** [comment]
However, your model can work. Can u adapt to support Mixamo fbx as well? I don't know what 's lack here, theoretically it should be same format.
<img width="752" alt="image" src="https://user-images.githubusercontent.com/21303438/170857435-72f41fbc-8ca7-40c6-9128-e919588113e0.png">
